### ISSUE TITLE
Error on loading, no list shown

### ISSUE THREAD

**Issue by moFries** [funsocietyirc/MMM-Wunderlist-Enhanced#10]
Hi, I get the following error:

> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | there was a Wunderlist problem 401
> 0|mm       | TypeError: Cannot read property 'users' of undefined
> 0|mm       |     at Class.getUsers (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_helper.js:30:28)
> 0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_helper.js:122:14)
> 0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:103:10)
> 0|mm       |     at emitTwo (events.js:106:13)
> 0|mm       |     at Socket.emit (events.js:191:7)
> 0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:503:12
> 0|mm       |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
> 0|mm       |     at process._tickCallback (internal/process/next_tick.js:98:9)

On the mirror, only the headline is shown, this is my config:

![grafik](https://user-images.githubusercontent.com/27133126/32865251-9cbdcfd8-ca62-11e7-8142-c0cfb8678ef3.png)

**Comment by hsukup1** [comment]
I also have this problem...but I believe it has something to do with install error.

~/MagicMirror/config.js
```
{
	module: "MMM-Wunderlist-Enhanced",
	position: "top-right",
	header: "Wunderlist",
	config: {
		accessToken: "accessToken", //fetched from [here](https://developer.wunderlist.com/apps/new)
		cliendID: "clientID", //fetched from [here](https://developer.wunderlist.com/apps/new)
		lists: ["Super Foods", "Torpin's", "To-Do"],
		order: "normal",
		maximumEntries: "60",
		interval: "60", //int in seconds
		fade: "true",
		fadePoint: "0.25",
		spaced: "false",
		showAssignee: "true", //show due date of task
		iconPosition: "left",
		showBullets: "true",
	},
},
```

**Comment by gpoprox** [comment]
this is 2 years old,. but i just had the *same* problem and there was no help. I had this same issue. You likely went to the site for the accessToken and copied in your Client Secret. 
You need to click "create access token"   then it will display the access token on top of the page.
