### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by alberttwong** [funsocietyirc/MMM-Wunderlist-Enhanced#2]
```
0|mm       | TypeError: Cannot read property '0' of undefined
0|mm       |     at /home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_helper.js:33:33
0|mm       |     at Array.forEach (native)
0|mm       |     at child.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_helper.js:32:13)
0|mm       |     at child.invoke (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:69:40)
0|mm       |     at child.trigger (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:48:12)
0|mm       |     at child.complete [as resolve] (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:126:10)
0|mm       |     at child.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderlist/public/io/IO.js:200:18)
0|mm       |     at child.invoke (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:69:40)
0|mm       |     at child.trigger (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:48:12)
0|mm       |     at child.complete [as resolve] (/home/pi/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_modules/wunderbits.core/public/WBDeferred.js:126:10)
```

**Comment by alberttwong** [comment]
here is my config.js

```
                {
                        module: "MMM-Wunderlist-Enhanced",
                        position: "top_right",
                        header: "Wunderlist",
                        config: {
                                accessToken: "5f6f8b5972470536222ac5f0ab03230bbbcc5279f2aaa3c90f66db780bb1",
                                clientID: "da50f5c13e5c25f87c51",
                                lists: ["Inbox","House to do","To do before leaving"]
                        }
                },
```

**Comment by davericher** [comment]
Hey, sorry for the delay. Will take a look tomorrow!

**Comment by PatrickGlatz** [comment]
I do have the EXACT same problem. Somewhen 6 months ago everything was working. Would you mind to have a look into this?

**Comment by flatiron23** [comment]
Hi, are there any updates about this issue? I am facing the same problem. Thank you in advance.

**Comment by sprestel** [comment]
+1

**Comment by lastcoolnameleft** [comment]
I don't know if this is the true fix for the problem; however, I edited the file `~/MagicMirror/modules/MMM-Wunderlist-Enhanced/node_helper.js` and went to line 32 and removed the `[0]` at the end of the line.  So, now it looks like:

```
    ret[user.id] = user.name
```

The error has gone away for me.
